/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Check API and database connectivity.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Semantic search over job postings with optional RAG generation.
         *
         *     When generate=True (default), returns an LLM-generated answer with sources.
         *     When generate=False, returns just the ranked search results.
         */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match/{posting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Match
         * @description Match a specific posting against the user profile.
         */
        get: operations["match_match__posting_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gaps
         * @description Aggregate skill gaps across all (or filtered) postings.
         */
        get: operations["gaps_gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/top-skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Top Skills
         * @description Top-N skills with must-have / nice-to-have split (DASH-01).
         *
         *     Soft skills hidden by default (D-13); pass ``?include_soft=true`` to include.
         *     Returns ``DashboardTopSkillsResponse`` with named OpenAPI schema (drives
         *     openapi-typescript codegen).
         */
        get: operations["dashboard_top_skills_dashboard_top_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/salary-bands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Salary Bands
         * @description Salary percentiles p25/p50/p75 via PostgreSQL ``percentile_cont`` (DASH-02).
         *
         *     Returns ``DashboardSalaryBandsResponse``; ``p25/p50/p75`` are ``int | None``
         *     (NULL when the filter matches zero salary-bearing postings - RESEARCH Pitfall 2).
         *     Per-period normalization: ``month`` -> x12; ``hour`` rows excluded (Pitfall 3).
         */
        get: operations["dashboard_salary_bands_dashboard_salary_bands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/cv-vs-market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Cv Vs Market
         * @description CV-vs-market aggregate match score (DASH-03).
         *
         *     D-12 zero-postings contract: when the filter matches zero postings, returns
         *     ``{mean_score: null, postings_compared: 0, top_missing_must_have: []}`` with
         *     HTTP 200 (NOT 404 like ``/gaps``).
         *
         *     Uses the existing ``match_posting()`` formula unchanged (D-10).
         */
        get: operations["dashboard_cv_vs_market_dashboard_cv_vs_market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agent Query
         * @description Run the LangGraph agent to completion on a single query.
         */
        post: operations["agent_query_agent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent Stream
         * @description Stream agent execution as SSE: typed events + heartbeat + 60s timeout + drain.
         *
         *     The handler wraps the Plan 04 ``stream_agent`` async iterator in
         *     ``asyncio.timeout(settings.agent_timeout_seconds)`` (D-25) so a runaway
         *     LangGraph reasoning loop cannot block forever. Three exception branches
         *     each emit a typed ``ErrorEvent`` (D-19) before closing:
         *
         *     - ``TimeoutError`` → ``reason="agent_timeout"``
         *     - ``CancelledError`` → ``reason="shutdown"`` (then re-raises so sse-starlette
         *       can complete the cancellation handshake)
         *     - any other ``Exception`` → ``reason="internal"`` with sanitized message
         *
         *     The current task is registered in ``app.state.active_streams`` on entry
         *     and discarded in ``finally`` — Plan 05's lifespan shutdown drains this set
         *     via ``asyncio.gather(*active_streams)`` with a 30s grace period (D-17).
         *
         *     sse-starlette's ``ping_message_factory`` is overridden so the keep-alive
         *     is a real ``event: heartbeat`` rather than a comment-only ``:ping`` (D-15).
         *     Defensive headers (``X-Accel-Buffering: no`` + ``Content-Encoding: identity``)
         *     prevent reverse-proxy/CDN buffering and accidental compression that would
         *     break EventSource parsing (D-18 / Pitfall 6).
         */
        get: operations["agent_stream_agent_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest
         * @description Ingest a single job posting markdown file via the async pipeline.
         *
         *     Pre-Plan-06, this route called ``ingest_file(SessionLocal(), tmp_path)`` —
         *     Plan 03's rewrap of ``ingest_file`` uses ``asyncio.run`` internally, which
         *     raises ``RuntimeError`` when called from an already-running event loop
         *     (i.e. inside any ``async def`` route). Plan 06 closes the latent crash by
         *     calling the async ``ingest_from_source`` directly with the request's
         *     AsyncSession dependency (D-24).
         *
         *     Error strings in ``error_details`` are sanitized via ``_sanitize`` (T-06-06)
         *     so per-source extraction failures cannot leak stack traces to the API
         *     boundary — same helper used by the ``/agent/stream`` error event path.
         *
         *     The ``user_id`` dep is wired so future plans (Phase 7 PROF-01 onward) can
         *     scope ingestion writes to a user without a signature change. Today the
         *     value is the single seeded user; the dep itself is the multi-tenancy hook.
         */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentQuery */
        AgentQuery: {
            /** Query */
            query: string;
        };
        /** Body_ingest_ingest_post */
        Body_ingest_ingest_post: {
            /** File */
            file: string;
        };
        /**
         * CountryFilter
         * @description Canonical 4-value country filter (D-07).
         *
         *     PL/DE: exact ISO-3166 alpha-2 match.
         *     EU:    union of EU-27 ISO codes OR location_region == 'EU' (catches NULL-country
         *            "Remote (EU)" postings per Phase 2 D-09).
         *     WW:    no filter (default; matches Worldwide).
         * @enum {string}
         */
        CountryFilter: "PL" | "DE" | "EU" | "WW";
        /**
         * DashboardCvMatchResponse
         * @description GET /dashboard/cv-vs-market response.
         *
         *     `mean_score` is `float | None` because D-12 zero-postings case returns
         *     `{mean_score: None, postings_compared: 0, top_missing_must_have: []}` with
         *     HTTP 200 (NOT 404).
         */
        DashboardCvMatchResponse: {
            /**
             * Mean Score
             * @description Arithmetic mean of per-posting match_posting() scores; None when postings_compared == 0 (D-12)
             */
            mean_score: number | null;
            /**
             * Postings Compared
             * @description Number of filtered postings compared against the profile
             */
            postings_compared: number;
            /**
             * Top Missing Must Have
             * @description Top 3 missing must-have skills ranked by frequency (Counter.most_common(3))
             */
            top_missing_must_have: components["schemas"]["MissingSkillItem"][];
        };
        /**
         * DashboardSalaryBandsResponse
         * @description GET /dashboard/salary-bands response.
         *
         *     Percentile fields are `int | None` because PostgreSQL `percentile_cont` returns
         *     NULL on empty result sets (RESEARCH Pitfall 2). The frontend reads `p50 is null`
         *     as the empty-state condition.
         */
        DashboardSalaryBandsResponse: {
            /**
             * P25
             * @description 25th percentile annual salary in EUR
             */
            p25: number | null;
            /**
             * P50
             * @description Median (50th percentile) annual salary in EUR
             */
            p50: number | null;
            /**
             * P75
             * @description 75th percentile annual salary in EUR
             */
            p75: number | null;
            /**
             * Postings With Salary
             * @description Number of filtered postings that had salary data (numerator of sample-size footnote)
             */
            postings_with_salary: number;
            /**
             * Total Postings
             * @description Total filtered postings (denominator of sample-size footnote)
             */
            total_postings: number;
            /**
             * Currency
             * @description ISO 4217 currency code; v1 hardcodes EUR
             * @default EUR
             */
            currency: string;
        };
        /**
         * DashboardTopSkillsResponse
         * @description GET /dashboard/top-skills response.
         */
        DashboardTopSkillsResponse: {
            /**
             * Skills
             * @description Top-N skills (capped at the `limit` query param) ordered by total DESC
             */
            skills: components["schemas"]["TopSkillItem"][];
            /**
             * Total Postings
             * @description Total postings matching the filter (footnote denominator)
             */
            total_postings: number;
            /**
             * Unique Skills
             * @description Distinct skill count (after soft-skill filter, if applied)
             */
            unique_skills: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MissingSkillItem
         * @description One row in the cv-vs-market top-3 missing must-have list.
         */
        MissingSkillItem: {
            /**
             * Skill
             * @description Missing must-have skill identifier
             */
            skill: string;
            /**
             * Count
             * @description Number of filtered postings missing this must-have
             */
            count: number;
            /**
             * Percentage
             * @description count / total_postings * 100, rounded to 1 decimal
             */
            percentage: number;
        };
        /**
         * RemoteFilter
         * @description 3-state remote-policy tri-toggle (D-09).
         *
         *     any:        no filter (default).
         *     remote:     remote_policy = 'remote'.
         *     non_remote: remote_policy IN ('hybrid', 'onsite').
         * @enum {string}
         */
        RemoteFilter: "any" | "remote" | "non_remote";
        /**
         * Seniority
         * @enum {string}
         */
        Seniority: "junior" | "mid" | "senior" | "staff" | "lead" | "unknown";
        /**
         * TopSkillItem
         * @description One row of the top-skills aggregate.
         */
        TopSkillItem: {
            /**
             * Skill
             * @description Skill identifier (technical, mono-font in UI)
             */
            skill: string;
            /**
             * Must Count
             * @description Number of postings where this skill is must-have
             */
            must_count: number;
            /**
             * Nice Count
             * @description Number of postings where this skill is nice-to-have
             */
            nice_count: number;
            /**
             * Total
             * @description must_count + nice_count
             */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ErrorEvent
         * @description Typed error event (D-16, D-17, D-19).
         *
         *     Wire shape: ``{"type": "error", "reason": "<literal>", "message": "<str>"}`` —
         *     emitted by the route handler's except blocks (Plan 06), NOT by ``stream_agent``.
         *     The ``reason`` field is a closed ``Literal`` set so frontends can branch
         *     deterministically on retry-vs-fatal classification.
         *
         *     ``message`` MUST be a sanitized human-readable string — NEVER a stack trace
         *     (T-04-01). The route handler runs ``_sanitize(exc)`` before constructing this
         *     event.
         */
        ErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /**
             * Reason
             * @description Machine-readable error kind (closed Literal set per D-19)
             * @enum {string}
             */
            reason: "agent_timeout" | "shutdown" | "llm_error" | "internal";
            /**
             * Message
             * @description Sanitized human-readable message — NEVER a stack trace
             */
            message: string;
        };
        /**
         * FinalEvent
         * @description Stream-complete marker.
         *
         *     Wire shape: ``{"type": "final", "content": "<full-message>"}`` — matches the
         *     dict yielded by ``agent/stream.py`` line 62. ``content`` is the concatenation
         *     of all token chunks emitted during the stream.
         */
        FinalEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "final";
            /**
             * Content
             * @description Synthesized final assistant message
             */
            content: string;
        };
        /**
         * HeartbeatEvent
         * @description 15s liveness ping (D-15).
         *
         *     Wire shape: ``{"type": "heartbeat", "ts": "<ISO-8601>"}`` — emitted by the
         *     route handler's sse-starlette ``ping_message_factory`` (Plan 06), NOT by
         *     ``stream_agent``. The frontend may surface this as a liveness indicator or
         *     silently consume it.
         */
        HeartbeatEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "heartbeat";
            /**
             * Ts
             * @description ISO-8601 timestamp at emit time
             */
            ts: string;
        };
        /**
         * TokenEvent
         * @description Incremental assistant text chunk.
         *
         *     Wire shape: ``{"type": "token", "content": "<chunk>"}`` — matches the dict
         *     yielded by ``agent/stream.py`` line 42.
         */
        TokenEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "token";
            /**
             * Content
             * @description Assistant text chunk
             */
            content: string;
        };
        /**
         * ToolEndEvent
         * @description Tool invocation has completed.
         *
         *     Wire shape: ``{"type": "tool_end", "name": "<tool>", "output": "<str>"}`` —
         *     matches the dict yielded by ``agent/stream.py`` lines 56-60. ``output`` is
         *     stringified at the source; structured outputs lose fidelity through ``str()``
         *     (T-04-03 accepted tradeoff).
         */
        ToolEndEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_end";
            /**
             * Name
             * @description Tool function name
             */
            name: string;
            /**
             * Output
             * @description Tool return value (stringified)
             */
            output: string;
        };
        /**
         * ToolStartEvent
         * @description Tool invocation has begun.
         *
         *     Wire shape: ``{"type": "tool_start", "name": "<tool>", "args": {...}|null}`` —
         *     matches the dict yielded by ``agent/stream.py`` lines 45-49. ``args`` is
         *     optional because LangGraph may not always supply tool inputs.
         */
        ToolStartEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_start";
            /**
             * Name
             * @description Tool function name
             */
            name: string;
            /**
             * Args
             * @description Tool arguments (JSON)
             */
            args?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
                seniority?: string | null;
                remote?: string | null;
                min_salary?: number | null;
                generate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_match__posting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                posting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gaps_gaps_get: {
        parameters: {
            query?: {
                seniority?: string | null;
                remote?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_top_skills_dashboard_top_skills_get: {
        parameters: {
            query?: {
                country?: components["schemas"]["CountryFilter"];
                seniority?: components["schemas"]["Seniority"] | null;
                remote?: components["schemas"]["RemoteFilter"];
                include_soft?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardTopSkillsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_salary_bands_dashboard_salary_bands_get: {
        parameters: {
            query?: {
                country?: components["schemas"]["CountryFilter"];
                seniority?: components["schemas"]["Seniority"] | null;
                remote?: components["schemas"]["RemoteFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSalaryBandsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_cv_vs_market_dashboard_cv_vs_market_get: {
        parameters: {
            query?: {
                country?: components["schemas"]["CountryFilter"];
                seniority?: components["schemas"]["Seniority"] | null;
                remote?: components["schemas"]["RemoteFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardCvMatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_query_agent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_stream_agent_stream_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream of AgentEvent variants (token, tool_start, tool_end, heartbeat, error, final) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": components["schemas"]["TokenEvent"] | components["schemas"]["ToolStartEvent"] | components["schemas"]["ToolEndEvent"] | components["schemas"]["HeartbeatEvent"] | components["schemas"]["ErrorEvent"] | components["schemas"]["FinalEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
